// Code generated by internal/gen from contract/template-variables.json; DO NOT EDIT.
//
// Typed builders constructing an EmailRequest for a specific messageId. Each
// owns the exact messageId and context keys the template expects. To change a
// builder, change the template (and the manifest) and regenerate:
//
//	go run ./internal/gen
//
// For a template without a typed builder, use Message().

package client

// Message builds a request for an arbitrary messageId with a raw context map.
// Prefer a typed builder when one exists.
func Message(messageId string, to To, context map[string]any) EmailRequest {
	if context == nil {
		context = map[string]any{}
	}
	return EmailRequest{
		MessageId:  messageId,
		Recipients: []Recipient{to},
		Context:    context,
	}
}

// AddedToOrganizationArgs are the variables for the "added-to-organization" template.
type AddedToOrganizationArgs struct {
	Administrator      string
	CustomMessage      string
	Host               string
	OrganizationName   string
	OrganizationNodeId string
}

// AddedToOrganization builds the "added-to-organization" email.
func AddedToOrganization(to To, args AddedToOrganizationArgs) EmailRequest {
	return Message("added-to-organization", to, map[string]any{
		"administrator":      args.Administrator,
		"customMessage":      args.CustomMessage,
		"host":               args.Host,
		"organizationName":   args.OrganizationName,
		"organizationNodeId": args.OrganizationNodeId,
	})
}

// AddedToTeamArgs are the variables for the "added-to-team" template.
type AddedToTeamArgs struct {
	Administrator      string
	Host               string
	OrganizationNodeId string
	TeamName           string
}

// AddedToTeam builds the "added-to-team" email.
func AddedToTeam(to To, args AddedToTeamArgs) EmailRequest {
	return Message("added-to-team", to, map[string]any{
		"administrator":      args.Administrator,
		"host":               args.Host,
		"organizationNodeId": args.OrganizationNodeId,
		"teamName":           args.TeamName,
	})
}

// ChangeOfDatasetOwnerArgs are the variables for the "change-of-dataset-owner" template.
type ChangeOfDatasetOwnerArgs struct {
	DatasetName        string
	DatasetNodeId      string
	Host               string
	OrganizationName   string
	OrganizationNodeId string
	PreviousOwnerName  string
}

// ChangeOfDatasetOwner builds the "change-of-dataset-owner" email.
func ChangeOfDatasetOwner(to To, args ChangeOfDatasetOwnerArgs) EmailRequest {
	return Message("change-of-dataset-owner", to, map[string]any{
		"datasetName":        args.DatasetName,
		"datasetNodeId":      args.DatasetNodeId,
		"host":               args.Host,
		"organizationName":   args.OrganizationName,
		"organizationNodeId": args.OrganizationNodeId,
		"previousOwnerName":  args.PreviousOwnerName,
	})
}

// DatasetEmbargoAcceptedArgs are the variables for the "dataset-embargo-accepted" template.
type DatasetEmbargoAcceptedArgs struct {
	DatasetName string
	EmbargoDate string
}

// DatasetEmbargoAccepted builds the "dataset-embargo-accepted" email.
func DatasetEmbargoAccepted(to To, args DatasetEmbargoAcceptedArgs) EmailRequest {
	return Message("dataset-embargo-accepted", to, map[string]any{
		"datasetName": args.DatasetName,
		"embargoDate": args.EmbargoDate,
	})
}

// DatasetProposalAcceptedArgs are the variables for the "dataset-proposal-accepted" template.
type DatasetProposalAcceptedArgs struct {
	AppURL                 string
	ProposalTitle          string
	WelcomeWorkspaceNodeId string
	WorkspaceName          string
}

// DatasetProposalAccepted builds the "dataset-proposal-accepted" email.
func DatasetProposalAccepted(to To, args DatasetProposalAcceptedArgs) EmailRequest {
	return Message("dataset-proposal-accepted", to, map[string]any{
		"AppURL":                 args.AppURL,
		"ProposalTitle":          args.ProposalTitle,
		"WelcomeWorkspaceNodeId": args.WelcomeWorkspaceNodeId,
		"WorkspaceName":          args.WorkspaceName,
	})
}

// DatasetProposalRejectedArgs are the variables for the "dataset-proposal-rejected" template.
type DatasetProposalRejectedArgs struct {
	AppURL                 string
	ProposalTitle          string
	WelcomeWorkspaceNodeId string
	WorkspaceName          string
}

// DatasetProposalRejected builds the "dataset-proposal-rejected" email.
func DatasetProposalRejected(to To, args DatasetProposalRejectedArgs) EmailRequest {
	return Message("dataset-proposal-rejected", to, map[string]any{
		"AppURL":                 args.AppURL,
		"ProposalTitle":          args.ProposalTitle,
		"WelcomeWorkspaceNodeId": args.WelcomeWorkspaceNodeId,
		"WorkspaceName":          args.WorkspaceName,
	})
}

// DatasetProposalSubmittedArgs are the variables for the "dataset-proposal-submitted" template.
type DatasetProposalSubmittedArgs struct {
	AppURL          string
	AuthorEmail     string
	AuthorName      string
	ProposalTitle   string
	WorkspaceName   string
	WorkspaceNodeId string
}

// DatasetProposalSubmitted builds the "dataset-proposal-submitted" email.
func DatasetProposalSubmitted(to To, args DatasetProposalSubmittedArgs) EmailRequest {
	return Message("dataset-proposal-submitted", to, map[string]any{
		"AppURL":          args.AppURL,
		"AuthorEmail":     args.AuthorEmail,
		"AuthorName":      args.AuthorName,
		"ProposalTitle":   args.ProposalTitle,
		"WorkspaceName":   args.WorkspaceName,
		"WorkspaceNodeId": args.WorkspaceNodeId,
	})
}

// DatasetProposalWithdrawnArgs are the variables for the "dataset-proposal-withdrawn" template.
type DatasetProposalWithdrawnArgs struct {
	AppURL          string
	AuthorEmail     string
	AuthorName      string
	ProposalTitle   string
	WorkspaceName   string
	WorkspaceNodeId string
}

// DatasetProposalWithdrawn builds the "dataset-proposal-withdrawn" email.
func DatasetProposalWithdrawn(to To, args DatasetProposalWithdrawnArgs) EmailRequest {
	return Message("dataset-proposal-withdrawn", to, map[string]any{
		"AppURL":          args.AppURL,
		"AuthorEmail":     args.AuthorEmail,
		"AuthorName":      args.AuthorName,
		"ProposalTitle":   args.ProposalTitle,
		"WorkspaceName":   args.WorkspaceName,
		"WorkspaceNodeId": args.WorkspaceNodeId,
	})
}

// DatasetPublicationAcceptedArgs are the variables for the "dataset-publication-accepted" template.
type DatasetPublicationAcceptedArgs struct {
	DatasetName  string
	Date         string
	ReviewerName string
}

// DatasetPublicationAccepted builds the "dataset-publication-accepted" email.
func DatasetPublicationAccepted(to To, args DatasetPublicationAcceptedArgs) EmailRequest {
	return Message("dataset-publication-accepted", to, map[string]any{
		"datasetName":  args.DatasetName,
		"date":         args.Date,
		"reviewerName": args.ReviewerName,
	})
}

// DatasetPublicationInReviewArgs are the variables for the "dataset-publication-in-review" template.
type DatasetPublicationInReviewArgs struct {
	DatasetName        string
	DatasetNodeId      string
	Date               string
	Host               string
	OrganizationNodeId string
	OwnerName          string
}

// DatasetPublicationInReview builds the "dataset-publication-in-review" email.
func DatasetPublicationInReview(to To, args DatasetPublicationInReviewArgs) EmailRequest {
	return Message("dataset-publication-in-review", to, map[string]any{
		"datasetName":        args.DatasetName,
		"datasetNodeId":      args.DatasetNodeId,
		"date":               args.Date,
		"host":               args.Host,
		"organizationNodeId": args.OrganizationNodeId,
		"ownerName":          args.OwnerName,
	})
}

// DatasetRevisionArgs are the variables for the "dataset-revision" template.
type DatasetRevisionArgs struct {
	DatasetNodeId      string
	DiscoverDatasetId  string
	DiscoverHost       string
	Host               string
	OrganizationNodeId string
}

// DatasetRevision builds the "dataset-revision" email.
func DatasetRevision(to To, args DatasetRevisionArgs) EmailRequest {
	return Message("dataset-revision", to, map[string]any{
		"datasetNodeId":      args.DatasetNodeId,
		"discoverDatasetId":  args.DiscoverDatasetId,
		"discoverHost":       args.DiscoverHost,
		"host":               args.Host,
		"organizationNodeId": args.OrganizationNodeId,
	})
}

// DatasetRevisionNeededArgs are the variables for the "dataset-revision-needed" template.
type DatasetRevisionNeededArgs struct {
	DatasetName        string
	DatasetNodeId      string
	Date               string
	Host               string
	Message            string
	OrganizationNodeId string
	ReviewerName       string
}

// DatasetRevisionNeeded builds the "dataset-revision-needed" email.
func DatasetRevisionNeeded(to To, args DatasetRevisionNeededArgs) EmailRequest {
	return Message("dataset-revision-needed", to, map[string]any{
		"datasetName":        args.DatasetName,
		"datasetNodeId":      args.DatasetNodeId,
		"date":               args.Date,
		"host":               args.Host,
		"message":            args.Message,
		"organizationNodeId": args.OrganizationNodeId,
		"reviewerName":       args.ReviewerName,
	})
}

// DatasetSubmittedForReviewArgs are the variables for the "dataset-submitted-for-review" template.
type DatasetSubmittedForReviewArgs struct {
	DatasetName        string
	DatasetNodeId      string
	Date               string
	Host               string
	OrganizationName   string
	OrganizationNodeId string
	OwnerEmailAddress  string
	OwnerName          string
}

// DatasetSubmittedForReview builds the "dataset-submitted-for-review" email.
func DatasetSubmittedForReview(to To, args DatasetSubmittedForReviewArgs) EmailRequest {
	return Message("dataset-submitted-for-review", to, map[string]any{
		"datasetName":        args.DatasetName,
		"datasetNodeId":      args.DatasetNodeId,
		"date":               args.Date,
		"host":               args.Host,
		"organizationName":   args.OrganizationName,
		"organizationNodeId": args.OrganizationNodeId,
		"ownerEmailAddress":  args.OwnerEmailAddress,
		"ownerName":          args.OwnerName,
	})
}

// EmailAddressChangedArgs are the variables for the "email-address-changed" template.
type EmailAddressChangedArgs struct {
	CurrentEmailAddress  string
	PreviousEmailAddress string
	TransactionNumber    string
}

// EmailAddressChanged builds the "email-address-changed" email.
func EmailAddressChanged(to To, args EmailAddressChangedArgs) EmailRequest {
	return Message("email-address-changed", to, map[string]any{
		"currentEmailAddress":  args.CurrentEmailAddress,
		"previousEmailAddress": args.PreviousEmailAddress,
		"transactionNumber":    args.TransactionNumber,
	})
}

// EmbargoAccessApprovedArgs are the variables for the "embargo-access-approved" template.
type EmbargoAccessApprovedArgs struct {
	DatasetName       string
	Date              string
	DiscoverDatasetId string
	DiscoverHost      string
	ManagerName       string
}

// EmbargoAccessApproved builds the "embargo-access-approved" email.
func EmbargoAccessApproved(to To, args EmbargoAccessApprovedArgs) EmailRequest {
	return Message("embargo-access-approved", to, map[string]any{
		"datasetName":       args.DatasetName,
		"date":              args.Date,
		"discoverDatasetId": args.DiscoverDatasetId,
		"discoverHost":      args.DiscoverHost,
		"managerName":       args.ManagerName,
	})
}

// EmbargoAccessDeniedArgs are the variables for the "embargo-access-denied" template.
type EmbargoAccessDeniedArgs struct {
	DatasetName string
	Date        string
	ManagerName string
}

// EmbargoAccessDenied builds the "embargo-access-denied" email.
func EmbargoAccessDenied(to To, args EmbargoAccessDeniedArgs) EmailRequest {
	return Message("embargo-access-denied", to, map[string]any{
		"datasetName": args.DatasetName,
		"date":        args.Date,
		"managerName": args.ManagerName,
	})
}

// EmbargoAccessRequestedArgs are the variables for the "embargo-access-requested" template.
type EmbargoAccessRequestedArgs struct {
	DatasetName        string
	DatasetNodeId      string
	Date               string
	Host               string
	OrganizationNodeId string
	UserName           string
}

// EmbargoAccessRequested builds the "embargo-access-requested" email.
func EmbargoAccessRequested(to To, args EmbargoAccessRequestedArgs) EmailRequest {
	return Message("embargo-access-requested", to, map[string]any{
		"datasetName":        args.DatasetName,
		"datasetNodeId":      args.DatasetNodeId,
		"date":               args.Date,
		"host":               args.Host,
		"organizationNodeId": args.OrganizationNodeId,
		"userName":           args.UserName,
	})
}

// EmbargoDatasetReleaseAcceptedArgs are the variables for the "embargo-dataset-release-accepted" template.
type EmbargoDatasetReleaseAcceptedArgs struct {
	DatasetName  string
	Date         string
	ReviewerName string
}

// EmbargoDatasetReleaseAccepted builds the "embargo-dataset-release-accepted" email.
func EmbargoDatasetReleaseAccepted(to To, args EmbargoDatasetReleaseAcceptedArgs) EmailRequest {
	return Message("embargo-dataset-release-accepted", to, map[string]any{
		"datasetName":  args.DatasetName,
		"date":         args.Date,
		"reviewerName": args.ReviewerName,
	})
}

// EmbargoedDatasetReleasedArgs are the variables for the "embargoed-dataset-released" template.
type EmbargoedDatasetReleasedArgs struct {
	DatasetName       string
	DiscoverDatasetId string
	DiscoverHost      string
}

// EmbargoedDatasetReleased builds the "embargoed-dataset-released" email.
func EmbargoedDatasetReleased(to To, args EmbargoedDatasetReleasedArgs) EmailRequest {
	return Message("embargoed-dataset-released", to, map[string]any{
		"datasetName":       args.DatasetName,
		"discoverDatasetId": args.DiscoverDatasetId,
		"discoverHost":      args.DiscoverHost,
	})
}

// ErrorPublishingArgs are the variables for the "error-publishing" template.
type ErrorPublishingArgs struct {
	DatasetName string
}

// ErrorPublishing builds the "error-publishing" email.
func ErrorPublishing(to To, args ErrorPublishingArgs) EmailRequest {
	return Message("error-publishing", to, map[string]any{
		"datasetName": args.DatasetName,
	})
}

// InviteExternalExistingUserToDatasetArgs are the variables for the "invite-external-existing-user-to-dataset" template.
type InviteExternalExistingUserToDatasetArgs struct {
	CustomMessage        string
	DatasetName          string
	InvitingEmailAddress string
	InvitingPerson       string
	WorkspaceName        string
}

// InviteExternalExistingUserToDataset builds the "invite-external-existing-user-to-dataset" email.
func InviteExternalExistingUserToDataset(to To, args InviteExternalExistingUserToDatasetArgs) EmailRequest {
	return Message("invite-external-existing-user-to-dataset", to, map[string]any{
		"customMessage":        args.CustomMessage,
		"datasetName":          args.DatasetName,
		"invitingEmailAddress": args.InvitingEmailAddress,
		"invitingPerson":       args.InvitingPerson,
		"workspaceName":        args.WorkspaceName,
	})
}

// InviteExternalNewUserToDatasetArgs are the variables for the "invite-external-new-user-to-dataset" template.
type InviteExternalNewUserToDatasetArgs struct {
	CustomMessage        string
	DatasetName          string
	InvitingEmailAddress string
	InvitingPerson       string
	SetupAccountLink     string
	WorkspaceName        string
}

// InviteExternalNewUserToDataset builds the "invite-external-new-user-to-dataset" email.
func InviteExternalNewUserToDataset(to To, args InviteExternalNewUserToDatasetArgs) EmailRequest {
	return Message("invite-external-new-user-to-dataset", to, map[string]any{
		"customMessage":        args.CustomMessage,
		"datasetName":          args.DatasetName,
		"invitingEmailAddress": args.InvitingEmailAddress,
		"invitingPerson":       args.InvitingPerson,
		"setupAccountLink":     args.SetupAccountLink,
		"workspaceName":        args.WorkspaceName,
	})
}

// NotificationOfPublicationToContributorArgs are the variables for the "notification-of-publication-to-contributor" template.
type NotificationOfPublicationToContributorArgs struct {
	DatasetName       string
	DiscoverDatasetId string
	DiscoverHost      string
	OwnerName         string
}

// NotificationOfPublicationToContributor builds the "notification-of-publication-to-contributor" email.
func NotificationOfPublicationToContributor(to To, args NotificationOfPublicationToContributorArgs) EmailRequest {
	return Message("notification-of-publication-to-contributor", to, map[string]any{
		"datasetName":       args.DatasetName,
		"discoverDatasetId": args.DiscoverDatasetId,
		"discoverHost":      args.DiscoverHost,
		"ownerName":         args.OwnerName,
	})
}

// RehydrationCompleteArgs are the variables for the "rehydration-complete" template.
type RehydrationCompleteArgs struct {
	AWSRegion           string
	DatasetID           string
	DatasetVersionID    string
	RehydrationLocation string
}

// RehydrationComplete builds the "rehydration-complete" email.
func RehydrationComplete(to To, args RehydrationCompleteArgs) EmailRequest {
	return Message("rehydration-complete", to, map[string]any{
		"AWSRegion":           args.AWSRegion,
		"DatasetID":           args.DatasetID,
		"DatasetVersionID":    args.DatasetVersionID,
		"RehydrationLocation": args.RehydrationLocation,
	})
}

// RehydrationFailedArgs are the variables for the "rehydration-failed" template.
type RehydrationFailedArgs struct {
	DatasetID           string
	DatasetVersionID    string
	RequestID           string
	SupportEmailAddress string
}

// RehydrationFailed builds the "rehydration-failed" email.
func RehydrationFailed(to To, args RehydrationFailedArgs) EmailRequest {
	return Message("rehydration-failed", to, map[string]any{
		"DatasetID":           args.DatasetID,
		"DatasetVersionID":    args.DatasetVersionID,
		"RequestID":           args.RequestID,
		"SupportEmailAddress": args.SupportEmailAddress,
	})
}
