// Code generated by internal/gen from contract/template-variables.json; DO NOT EDIT.
//
// Typed builders mirroring the Go client. Regenerate with: go run ./internal/gen
// For a template without a typed builder, use Messages.build(...).

package com.pennsieve.email.client

import io.circe.Json

object Messages {

  /** Untyped escape hatch: build a request for an arbitrary messageId. Named
    * "build" rather than "message" so it never collides with a context key used
    * as a builder parameter (e.g. dataset-revision-needed has a "message" var).
    */
  def build(messageId: String, to: Recipient, context: Map[String, Json] = Map.empty): EmailRequest =
    EmailRequest(messageId = messageId, recipients = List(to), context = context)

  private def str(kvs: (String, String)*): Map[String, Json] =
    kvs.map { case (k, v) => k -> Json.fromString(v) }.toMap

  /** Builds the "added-to-organization" email. */
  def addedToOrganization(
      to: Recipient,
      administrator: String,
      customMessage: String,
      host: String,
      organizationName: String,
      organizationNodeId: String
  ): EmailRequest =
    build(
      "added-to-organization",
      to,
      str(
        "administrator" -> administrator,
        "customMessage" -> customMessage,
        "host" -> host,
        "organizationName" -> organizationName,
        "organizationNodeId" -> organizationNodeId
      )
    )

  /** Builds the "added-to-team" email. */
  def addedToTeam(
      to: Recipient,
      administrator: String,
      host: String,
      organizationNodeId: String,
      teamName: String
  ): EmailRequest =
    build(
      "added-to-team",
      to,
      str(
        "administrator" -> administrator,
        "host" -> host,
        "organizationNodeId" -> organizationNodeId,
        "teamName" -> teamName
      )
    )

  /** Builds the "change-of-dataset-owner" email. */
  def changeOfDatasetOwner(
      to: Recipient,
      datasetName: String,
      datasetNodeId: String,
      host: String,
      organizationName: String,
      organizationNodeId: String,
      previousOwnerName: String
  ): EmailRequest =
    build(
      "change-of-dataset-owner",
      to,
      str(
        "datasetName" -> datasetName,
        "datasetNodeId" -> datasetNodeId,
        "host" -> host,
        "organizationName" -> organizationName,
        "organizationNodeId" -> organizationNodeId,
        "previousOwnerName" -> previousOwnerName
      )
    )

  /** Builds the "dataset-embargo-accepted" email. */
  def datasetEmbargoAccepted(
      to: Recipient,
      datasetName: String,
      embargoDate: String
  ): EmailRequest =
    build(
      "dataset-embargo-accepted",
      to,
      str(
        "datasetName" -> datasetName,
        "embargoDate" -> embargoDate
      )
    )

  /** Builds the "dataset-proposal-accepted" email. */
  def datasetProposalAccepted(
      to: Recipient,
      AppURL: String,
      ProposalTitle: String,
      WelcomeWorkspaceNodeId: String,
      WorkspaceName: String
  ): EmailRequest =
    build(
      "dataset-proposal-accepted",
      to,
      str(
        "AppURL" -> AppURL,
        "ProposalTitle" -> ProposalTitle,
        "WelcomeWorkspaceNodeId" -> WelcomeWorkspaceNodeId,
        "WorkspaceName" -> WorkspaceName
      )
    )

  /** Builds the "dataset-proposal-rejected" email. */
  def datasetProposalRejected(
      to: Recipient,
      AppURL: String,
      ProposalTitle: String,
      WelcomeWorkspaceNodeId: String,
      WorkspaceName: String
  ): EmailRequest =
    build(
      "dataset-proposal-rejected",
      to,
      str(
        "AppURL" -> AppURL,
        "ProposalTitle" -> ProposalTitle,
        "WelcomeWorkspaceNodeId" -> WelcomeWorkspaceNodeId,
        "WorkspaceName" -> WorkspaceName
      )
    )

  /** Builds the "dataset-proposal-submitted" email. */
  def datasetProposalSubmitted(
      to: Recipient,
      AppURL: String,
      AuthorEmail: String,
      AuthorName: String,
      ProposalTitle: String,
      WorkspaceName: String,
      WorkspaceNodeId: String
  ): EmailRequest =
    build(
      "dataset-proposal-submitted",
      to,
      str(
        "AppURL" -> AppURL,
        "AuthorEmail" -> AuthorEmail,
        "AuthorName" -> AuthorName,
        "ProposalTitle" -> ProposalTitle,
        "WorkspaceName" -> WorkspaceName,
        "WorkspaceNodeId" -> WorkspaceNodeId
      )
    )

  /** Builds the "dataset-proposal-withdrawn" email. */
  def datasetProposalWithdrawn(
      to: Recipient,
      AppURL: String,
      AuthorEmail: String,
      AuthorName: String,
      ProposalTitle: String,
      WorkspaceName: String,
      WorkspaceNodeId: String
  ): EmailRequest =
    build(
      "dataset-proposal-withdrawn",
      to,
      str(
        "AppURL" -> AppURL,
        "AuthorEmail" -> AuthorEmail,
        "AuthorName" -> AuthorName,
        "ProposalTitle" -> ProposalTitle,
        "WorkspaceName" -> WorkspaceName,
        "WorkspaceNodeId" -> WorkspaceNodeId
      )
    )

  /** Builds the "dataset-publication-accepted" email. */
  def datasetPublicationAccepted(
      to: Recipient,
      datasetName: String,
      date: String,
      reviewerName: String
  ): EmailRequest =
    build(
      "dataset-publication-accepted",
      to,
      str(
        "datasetName" -> datasetName,
        "date" -> date,
        "reviewerName" -> reviewerName
      )
    )

  /** Builds the "dataset-publication-in-review" email. */
  def datasetPublicationInReview(
      to: Recipient,
      datasetName: String,
      datasetNodeId: String,
      date: String,
      host: String,
      organizationNodeId: String,
      ownerName: String
  ): EmailRequest =
    build(
      "dataset-publication-in-review",
      to,
      str(
        "datasetName" -> datasetName,
        "datasetNodeId" -> datasetNodeId,
        "date" -> date,
        "host" -> host,
        "organizationNodeId" -> organizationNodeId,
        "ownerName" -> ownerName
      )
    )

  /** Builds the "dataset-revision" email. */
  def datasetRevision(
      to: Recipient,
      datasetNodeId: String,
      discoverDatasetId: String,
      discoverHost: String,
      host: String,
      organizationNodeId: String
  ): EmailRequest =
    build(
      "dataset-revision",
      to,
      str(
        "datasetNodeId" -> datasetNodeId,
        "discoverDatasetId" -> discoverDatasetId,
        "discoverHost" -> discoverHost,
        "host" -> host,
        "organizationNodeId" -> organizationNodeId
      )
    )

  /** Builds the "dataset-revision-needed" email. */
  def datasetRevisionNeeded(
      to: Recipient,
      datasetName: String,
      datasetNodeId: String,
      date: String,
      host: String,
      message: String,
      organizationNodeId: String,
      reviewerName: String
  ): EmailRequest =
    build(
      "dataset-revision-needed",
      to,
      str(
        "datasetName" -> datasetName,
        "datasetNodeId" -> datasetNodeId,
        "date" -> date,
        "host" -> host,
        "message" -> message,
        "organizationNodeId" -> organizationNodeId,
        "reviewerName" -> reviewerName
      )
    )

  /** Builds the "dataset-submitted-for-review" email. */
  def datasetSubmittedForReview(
      to: Recipient,
      datasetName: String,
      datasetNodeId: String,
      date: String,
      host: String,
      organizationName: String,
      organizationNodeId: String,
      ownerEmailAddress: String,
      ownerName: String
  ): EmailRequest =
    build(
      "dataset-submitted-for-review",
      to,
      str(
        "datasetName" -> datasetName,
        "datasetNodeId" -> datasetNodeId,
        "date" -> date,
        "host" -> host,
        "organizationName" -> organizationName,
        "organizationNodeId" -> organizationNodeId,
        "ownerEmailAddress" -> ownerEmailAddress,
        "ownerName" -> ownerName
      )
    )

  /** Builds the "email-address-changed" email. */
  def emailAddressChanged(
      to: Recipient,
      currentEmailAddress: String,
      previousEmailAddress: String,
      transactionNumber: String
  ): EmailRequest =
    build(
      "email-address-changed",
      to,
      str(
        "currentEmailAddress" -> currentEmailAddress,
        "previousEmailAddress" -> previousEmailAddress,
        "transactionNumber" -> transactionNumber
      )
    )

  /** Builds the "embargo-access-approved" email. */
  def embargoAccessApproved(
      to: Recipient,
      datasetName: String,
      date: String,
      discoverDatasetId: String,
      discoverHost: String,
      managerName: String
  ): EmailRequest =
    build(
      "embargo-access-approved",
      to,
      str(
        "datasetName" -> datasetName,
        "date" -> date,
        "discoverDatasetId" -> discoverDatasetId,
        "discoverHost" -> discoverHost,
        "managerName" -> managerName
      )
    )

  /** Builds the "embargo-access-denied" email. */
  def embargoAccessDenied(
      to: Recipient,
      datasetName: String,
      date: String,
      managerName: String
  ): EmailRequest =
    build(
      "embargo-access-denied",
      to,
      str(
        "datasetName" -> datasetName,
        "date" -> date,
        "managerName" -> managerName
      )
    )

  /** Builds the "embargo-access-requested" email. */
  def embargoAccessRequested(
      to: Recipient,
      datasetName: String,
      datasetNodeId: String,
      date: String,
      host: String,
      organizationNodeId: String,
      userName: String
  ): EmailRequest =
    build(
      "embargo-access-requested",
      to,
      str(
        "datasetName" -> datasetName,
        "datasetNodeId" -> datasetNodeId,
        "date" -> date,
        "host" -> host,
        "organizationNodeId" -> organizationNodeId,
        "userName" -> userName
      )
    )

  /** Builds the "embargo-dataset-release-accepted" email. */
  def embargoDatasetReleaseAccepted(
      to: Recipient,
      datasetName: String,
      date: String,
      reviewerName: String
  ): EmailRequest =
    build(
      "embargo-dataset-release-accepted",
      to,
      str(
        "datasetName" -> datasetName,
        "date" -> date,
        "reviewerName" -> reviewerName
      )
    )

  /** Builds the "embargoed-dataset-released" email. */
  def embargoedDatasetReleased(
      to: Recipient,
      datasetName: String,
      discoverDatasetId: String,
      discoverHost: String
  ): EmailRequest =
    build(
      "embargoed-dataset-released",
      to,
      str(
        "datasetName" -> datasetName,
        "discoverDatasetId" -> discoverDatasetId,
        "discoverHost" -> discoverHost
      )
    )

  /** Builds the "error-publishing" email. */
  def errorPublishing(
      to: Recipient,
      datasetName: String
  ): EmailRequest =
    build(
      "error-publishing",
      to,
      str(
        "datasetName" -> datasetName
      )
    )

  /** Builds the "invite-external-existing-user-to-dataset" email. */
  def inviteExternalExistingUserToDataset(
      to: Recipient,
      customMessage: String,
      datasetName: String,
      invitingEmailAddress: String,
      invitingPerson: String,
      workspaceName: String
  ): EmailRequest =
    build(
      "invite-external-existing-user-to-dataset",
      to,
      str(
        "customMessage" -> customMessage,
        "datasetName" -> datasetName,
        "invitingEmailAddress" -> invitingEmailAddress,
        "invitingPerson" -> invitingPerson,
        "workspaceName" -> workspaceName
      )
    )

  /** Builds the "invite-external-new-user-to-dataset" email. */
  def inviteExternalNewUserToDataset(
      to: Recipient,
      customMessage: String,
      datasetName: String,
      invitingEmailAddress: String,
      invitingPerson: String,
      setupAccountLink: String,
      workspaceName: String
  ): EmailRequest =
    build(
      "invite-external-new-user-to-dataset",
      to,
      str(
        "customMessage" -> customMessage,
        "datasetName" -> datasetName,
        "invitingEmailAddress" -> invitingEmailAddress,
        "invitingPerson" -> invitingPerson,
        "setupAccountLink" -> setupAccountLink,
        "workspaceName" -> workspaceName
      )
    )

  /** Builds the "notification-of-publication-to-contributor" email. */
  def notificationOfPublicationToContributor(
      to: Recipient,
      datasetName: String,
      discoverDatasetId: String,
      discoverHost: String,
      ownerName: String
  ): EmailRequest =
    build(
      "notification-of-publication-to-contributor",
      to,
      str(
        "datasetName" -> datasetName,
        "discoverDatasetId" -> discoverDatasetId,
        "discoverHost" -> discoverHost,
        "ownerName" -> ownerName
      )
    )

  /** Builds the "rehydration-complete" email. */
  def rehydrationComplete(
      to: Recipient,
      AWSRegion: String,
      DatasetID: String,
      DatasetVersionID: String,
      RehydrationLocation: String
  ): EmailRequest =
    build(
      "rehydration-complete",
      to,
      str(
        "AWSRegion" -> AWSRegion,
        "DatasetID" -> DatasetID,
        "DatasetVersionID" -> DatasetVersionID,
        "RehydrationLocation" -> RehydrationLocation
      )
    )

  /** Builds the "rehydration-failed" email. */
  def rehydrationFailed(
      to: Recipient,
      DatasetID: String,
      DatasetVersionID: String,
      RequestID: String,
      SupportEmailAddress: String
  ): EmailRequest =
    build(
      "rehydration-failed",
      to,
      str(
        "DatasetID" -> DatasetID,
        "DatasetVersionID" -> DatasetVersionID,
        "RequestID" -> RequestID,
        "SupportEmailAddress" -> SupportEmailAddress
      )
    )
}
